name: koppy-logs

services:
  db:
    container_name: koppy_logs_db
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: koppy_logs
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    container_name: koppy_logs_redis
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=redis
    volumes:
      - redis-data:/data


volumes:
  postgres_data:
  redis-data: